In [7]:
import torch_xla.core.xla_model as xm
import torch

device = xm.xla_device()
print(device)

xla:0


In [16]:
x=torch.tensor(3.0,requires_grad=True)

In [17]:
y=x**2

In [18]:
x # grad attribute creates a computation graph

tensor(3., requires_grad=True)

In [19]:
y #stored function to variables that have computation graph

tensor(9., grad_fn=<PowBackward0>)

In [20]:
y.backward() #calculates gradients in backward directions

In [21]:
x.grad

tensor(6.)

In [31]:
#ex2

a=torch.tensor(3.0,requires_grad=True)
b=a**2

In [32]:
c=torch.sin(b)

In [33]:
a

tensor(3., requires_grad=True)

In [34]:
b

tensor(9., grad_fn=<PowBackward0>)

In [35]:
c

tensor(0.4121, grad_fn=<SinBackward0>)

In [36]:
c.backward()

In [37]:
a.grad

tensor(-5.4668)

In [61]:
m=torch.tensor([1.0,2.0,3.0],requires_grad=True)
n=m**3

In [62]:
m

tensor([1., 2., 3.], requires_grad=True)

In [63]:
n

tensor([ 1.,  8., 27.], grad_fn=<PowBackward0>)

In [66]:
n.backward(gradient=torch.ones_like(n))

In [67]:
m.grad

tensor([ 3., 12., 27.])

In [70]:
##clearing grad
m.grad.zero_()


tensor([0., 0., 0.])

# Autograd in NN

In [75]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [76]:
prediction = model(data) # forward pass

In [77]:
loss = (prediction - labels).sum()
loss.backward() # backward pass
loss

tensor(-481.8192, grad_fn=<SumBackward0>)

In [78]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [79]:
optim.step() #gradient descent-The optimizer adjusts each parameter by its gradient stored in .grad.