In [1]:
import torch

In [2]:
print(torch.cuda.get_device_name())
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

Tesla T4
cuda


In [4]:
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out

In [6]:
features=torch.rand(10,5)

model=Model(features.shape[1])

model(features)

tensor([[0.3956],
        [0.4428],
        [0.4250],
        [0.4667],
        [0.4709],
        [0.4699],
        [0.4864],
        [0.3639],
        [0.3438],
        [0.5026]], grad_fn=<SigmoidBackward0>)

In [8]:
#model weights
model.linear.weight

Parameter containing:
tensor([[-0.2867, -0.2804,  0.3263, -0.4035,  0.0169]], requires_grad=True)

In [9]:
#bias factors
model.linear.bias

Parameter containing:
tensor([0.0988], requires_grad=True)

In [10]:
!pip install torchinfo

In [14]:
from torchinfo import summary
summary(model,input_size=(20,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [20, 1]                   --
├─Linear: 1-1                            [20, 1]                   6
├─Sigmoid: 1-2                           [20, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [26]:
class Model2(nn.Module):
    def __init__(self,num_features):

        super().__init__()
        self.linear1=nn.Linear(num_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)

        return out

In [27]:
features=torch.rand(10,5)

model2=Model2(features.shape[1])

In [28]:
model2(features)

tensor([[0.6269],
        [0.6269],
        [0.6269],
        [0.6269],
        [0.6269],
        [0.6269],
        [0.6269],
        [0.6268],
        [0.6269],
        [0.6269]], grad_fn=<SigmoidBackward0>)

In [31]:
model2.linear1.weight

Parameter containing:
tensor([[ 0.2966, -0.3726,  0.4058,  0.2069, -0.1411],
        [-0.0214, -0.1505, -0.2218, -0.4066, -0.0682],
        [-0.2099, -0.3123, -0.3359,  0.3057, -0.4279]], requires_grad=True)

# Sequential Container

In [3]:
import torch.nn as nn

In [13]:
class Model(nn.Module):

    def __init__(self,num_features):

        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self,features):
        out=self.network(features)

        return out

In [14]:
features=torch.rand(10,5)

model=Model(features.shape[1])
model(features)

tensor([[0.3671],
        [0.4439],
        [0.4460],
        [0.3946],
        [0.4489],
        [0.4447],
        [0.4676],
        [0.4279],
        [0.3840],
        [0.4181]], grad_fn=<SigmoidBackward0>)