In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)
print(torch.cuda.get_device_name(0))

cuda
Tesla T4


In [3]:
#Creating Tensors
a=torch.empty(2,3)
type(a)


torch.Tensor

In [4]:
#zero tensor
torch.zeros(2,4)

#ones
torch.ones(1,2)

#random values
torch.rand(2,3)

tensor([[0.8006, 0.2373, 0.3877],
        [0.1309, 0.1775, 0.6805]])

In [5]:
#reproducing same random number
torch.manual_seed(5)
torch.rand(2,2)

tensor([[0.8303, 0.1261],
        [0.9075, 0.8199]])

In [6]:
torch.manual_seed(5)
torch.rand(2,2)

tensor([[0.8303, 0.1261],
        [0.9075, 0.8199]])

In [7]:
#manual tensors
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [10]:
print("arange" , torch.arange(0,10,1))

print("linspace" , torch.linspace(0,10,10))

print("eye" , torch.eye(5))

print("full" , torch.full((2,2),5))

arange tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
linspace tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
full tensor([[5, 5],
        [5, 5]])


In [12]:
x=torch.tensor([[1,2],[2,3],[3,4]])
x.shape

torch.Size([3, 2])

In [15]:
torch.empty_like(x)

tensor([[7810763971874521088, 8319683848551211643],
        [3180222411935070754, 8391722768137527840],
        [7959390389040738153, 2318283094764429940]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [17]:
x.dtype

torch.int64

In [18]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
torch.tensor([1.0,2.0,3.0],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [20]:
x.to(torch.float64)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]], dtype=torch.float64)

# Mathematical Operations

In [33]:
x+2

x-2

x/2

x*2

(x*100)/3

x**2  #elementwise operations

tensor([[ 1,  4],
        [ 4,  9],
        [ 9, 16]])

In [34]:
torch.neg(x)

tensor([[-1, -2],
        [-2, -3],
        [-3, -4]])

In [35]:
torch.ceil(x)

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [37]:
torch.sum(x) #sum of tensor

tensor(15)

In [44]:
y=torch.rand(2,3,dtype=torch.float16)
torch.mean(y) #only on float dtype


tensor(0.6758, dtype=torch.float16)

In [46]:
torch.prod(y)

tensor(0.0278, dtype=torch.float16)

In [47]:
torch.std(y)

tensor(0.3237, dtype=torch.float16)

In [48]:
torch.var(y)

tensor(0.1047, dtype=torch.float16)

In [49]:
torch.argmax(x) #position of max element

tensor(5)

In [51]:
v1=torch.tensor([1,2,3])
v2=torch.tensor([4,5,6])
torch.dot(v1,v2)


tensor(32)

In [53]:
v1>v2 #comparison between two matrices

tensor([False, False, False])

# Activation Functions

In [54]:
torch.log(x)

tensor([[0.0000, 0.6931],
        [0.6931, 1.0986],
        [1.0986, 1.3863]])

In [55]:
torch.sigmoid(x)

tensor([[0.7311, 0.8808],
        [0.8808, 0.9526],
        [0.9526, 0.9820]])

In [57]:
torch.softmax(y,dim=1)

tensor([[0.3662, 0.1904, 0.4434],
        [0.2693, 0.3154, 0.4150]], dtype=torch.float16)

In [58]:
torch.relu(y)

tensor([[0.7534, 0.0996, 0.9448],
        [0.5552, 0.7134, 0.9878]], dtype=torch.float16)

# Inplace Operations

In [59]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.0407, 0.7850, 0.9752],
        [0.0903, 0.5273, 0.6794]])
tensor([[0.2639, 0.3906, 0.1661],
        [0.2636, 0.0442, 0.4884]])


In [60]:
m.add_(n)

tensor([[0.3046, 1.1756, 1.1413],
        [0.3540, 0.5715, 1.1678]])

In [63]:
m.relu_() #permanent changes by _ after operation name

tensor([[0.3046, 1.1756, 1.1413],
        [0.3540, 0.5715, 1.1678]])

In [64]:
#Cloning

p=m.clone()

In [65]:
p

tensor([[0.3046, 1.1756, 1.1413],
        [0.3540, 0.5715, 1.1678]])

# Using GPU for tensor operations

In [66]:
torch.rand((2,3),device=device)

tensor([[0.7660, 0.3875, 0.7305],
        [0.1861, 0.9196, 0.4495]], device='cuda:0')

In [68]:
b=m.to(device)

In [69]:
b+5

tensor([[5.3046, 6.1756, 6.1413],
        [5.3540, 5.5715, 6.1678]], device='cuda:0')

In [70]:
import time

size=10000

matrixcpu1=torch.randn(size,size)
matrixcpu2=torch.randn(size,size)

matrixgpu1=matrixcpu1.to(device)
matrixgpu2=matrixcpu2.to(device)

start_timecpu=time.time()
matrixcpu1.matmul(matrixcpu2)
end_time=time.time()
print(end_time-start_timecpu)

start_timegpu=time.time()
matrixgpu1.matmul(matrixgpu2)
end_time=time.time()
print(end_time-start_timegpu)


25.81475567817688
0.11809897422790527


In [71]:
#flatten

m.flatten()

tensor([0.3046, 1.1756, 1.1413, 0.3540, 0.5715, 1.1678])